name: 'Build and push'
description: 'Build and push Docker image to Docker Hub'
inputs:
  DOCKERHUB_USERNAME:
    description: 'Docker Hub username'
    required: true
  DOCKERHUB_TOKEN:
    description: 'Docker Hub token'
    required: true
runs:
  using: "composite"
  steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get latest tag
        shell: bash
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=${TAG:1}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: nkwd/gitlab-mcp:latest,nkwd/gitlab-mcp:${{ github.sha }},
                nkwd/gitlab-mcp:${{ env.TAG }}